# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.0.13"
    web.vm.network "forwarded_port", guest: 80, host: 80
    web.vm.provision "shell", inline: <<-SHELL
      echo "web" > /etc/hostname
      hostname -b web
      echo "192.168.0.12        clock" >> /etc/hosts
      echo "***> sudo apt-get update"; sudo apt-get update
      echo "***sudo apt-get install -y git***"; sudo apt-get install -y git
      echo "***git clone https://github.com/Brendapl/RelojWeb.git***"; git clone https://github.com/Brendapl/RelojWeb.git
      echo "***rm RelojWeb/*.js***"; rm RelojWeb/*.js
      echo "--> curl http://192.168.0.12:3000";  curl http://192.168.0.12:3000
        sudo cp -a RelojWeb/* /var/www/html
    SHELL
  end
  config.vm.define "clock" do |clock|
    clock.vm.box = "ubuntu/bionic64"
    clock.vm.network "private_network", ip: "192.168.0.12"
    clock.vm.network "forwarded_port", guest: 3000, host: 3000
    clock.vm.provision "shell", inline: <<-SHELL
      echo "clock" > /etc/hostname
      hostname -b clock
      echo "192.168.0.13        web" >> /etc/hosts
      echo "***> sudo apt-get update"; sudo apt-get update
      echo "***sudo apt-get install -y git***"; sudo apt-get install -y git
      echo "***> git clone https://github.com/Brendapl/RelojWeb.git"; git clone https://github.com/Brendapl/RelojWeb.git
      echo "***> cd RelojWeb"; cd RelojWeb
      echo "***> rm *.json"; rm *.json
      echo "***> node app.js"; node app.js &
    SHELL
  end
end